### ISSUE TITLE
Pip3: on terminal type: python3 get-pip.py

### ISSUE THREAD

**Issue by Aidanbar** [luismendozaignacio/spaminator#1]
A little confused on how to execute this. On the terminal it says it cannot find the file

**Comment by luismendozaignacio** [comment]
Is the issue with downloading pip3?

**Comment by aciomi** [comment]
> A little confused on how to execute this. On the terminal it says it cannot find the file 


Is the issue with downloading pip3?

**Comment by luismendozaignacio** [comment]
User did not respond for further help.
